### ISSUE TITLE
无法载入DLL, 开不到

### ISSUE THREAD

**Issue by zelda0079** [GangZhuo/BaiduPCS_NET#11]
我另外一台电脑出现这个情况
而旧版1.0.4版没事, 可以开, 只是不能登入
![default](https://cloud.githubusercontent.com/assets/19840375/24321864/032ba4e6-1192-11e7-92ad-f0046229d277.png)

**Comment by j4Uq** [comment]
我也遇到了这个问题
![default](https://cloud.githubusercontent.com/assets/6436073/24604678/5a4497b2-1898-11e7-9649-aa2cc23a5bf8.PNG)

**Comment by GangZhuo** [comment]
https://github.com/GangZhuo/BaiduPCS_NET/issues/13
