### ISSUE TITLE
win7系统下出现加载dll错误

### ISSUE THREAD

**Issue by test482** [GangZhuo/BaiduPCS_NET#13]
---------------------------

---------------------------
Can't create BaiduPCS: 无法加载 DLL“BaiduPCS.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
---------------------------
确定   
---------------------------
已经安装.net 4.6 运行库

**Comment by GangZhuo** [comment]
到 https://www.microsoft.com/zh-CN/download/details.aspx?id=48145 下载 vc_redist.x86.exe 安装后，应该就可以了。
