### ISSUE TITLE
如果帐号需要验证身份登入就会无法登入

### ISSUE THREAD

**Issue by zelda0079** [GangZhuo/BaiduPCS_NET#9]
如果帐号需要验证身份登入就会无法登入
例如手机或邮箱验证那种
我有1个帐号一定要验证无法取消

**Comment by HanryYu** [comment]
一样，一直登不进去，希望能解决

**Comment by GangZhuo** [comment]
fixed

**Comment by zelda0079** [comment]
感谢作者

**Comment by HanryYu** [comment]
感谢作者

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Gang Zhuo<mailto:notifications@github.com>
发送时间: 2017年3月22日 21:54
收件人: GangZhuo/BaiduPCS_NET<mailto:BaiduPCS_NET@noreply.github.com>
抄送: FishionYu<mailto:Fishion@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [GangZhuo/BaiduPCS_NET] 如果帐号需要验证身份登入就会无法登入 (#9)


fixed

―
